name = "suipe-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[dev]
local_protocol = "http"

[[d1_databases]]
binding = "DB"
database_name = "suipe"
database_id = "54dd4d52-1a8e-4315-84e7-39af6d010418"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "suipe-assets"
